# -*- coding: utf-8 -*-
# Copyright 2026 Morwi Encoders Consulting SA de CV
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl.html).
"""Fix the Studio-customized invoice QWeb reports for Odoo 19.

These reports (Factura Exportacion, Factura Dolares DVI[/copia], Factura
Dolares VECO[/con Comercio Exterior], Factura Nacional DVI[/Rev2], Factura
Nacional Veco copy(8)/Rev. Sep25) are `ir.ui.view` records generated by
Odoo Studio (module ``studio_customization``), not files tracked in this
repo. They still contained several patterns from Odoo <=16 that were
removed/renamed by Odoo 19:

- a stray ``style="color:#000000"`` attribute placed directly on a
  ``<t t-call="web.external_layout">`` node: any non ``t-`` attribute on a
  ``t-call`` is compiled as a python expression, and "color:#000000" isn't
  a valid expression.
- ``account.move.tax_totals_json`` (removed, replaced by the ``tax_totals``
  dict field, which also needs a ``currency`` value passed to
  ``account.document_tax_totals``).
- ``account.move._l10n_mx_edi_decode_cfdi()`` (removed, replaced by
  ``l10n_mx_edi.document._decode_cfdi_attachment()``).
- ``account.move._get_l10n_mx_edi_signed_edi_document()`` (removed).
- ``account.move._get_reconciled_info_JSON_values()`` (removed, replaced by
  the ``invoice_payments_widget`` field).
- ``account.move.l10n_mx_edi_origin`` (renamed to
  ``l10n_mx_edi_cfdi_origin``).
- ``account.move.l10n_mx_edi_cfdi_request`` (removed field, was used to
  decide whether to show the "signature required" banner).
- four of the reports never printed anything because they gated the
  document on ``o._get_name_invoice_report() == 'account.report_invoice_document'``,
  which is never true for an invoice whose CFDI was already stamped
  (l10n_mx_edi overrides that method to return
  ``'l10n_mx_edi.report_invoice_document'`` instead).
- ``account.move.line.display_type`` used to be ``False``/empty for a
  regular product line; Odoo 19 now sets it to ``'product'``. All ten
  documents guarded their line row with ``t-if="not line.display_type"``,
  which is now always false, so every invoice printed with an empty product
  table (subtotal/tax/total still computed fine since those come from
  ``tax_totals``, not from the line loop).
- the ``Odoo Studio: report_invoice_document copy(1) customization``
  overlay (inherited view on top of ``account.report_invoice_document_copy_1``,
  used by "Factura Nacional Veco copy(8)") references
  ``line.internal_note``, a field that doesn't exist (removed, or a custom
  field that was later deleted): the whole "Nota interna" column addition is
  dropped. The same overlay also overwrote a header ``<span>``'s ``t-field``
  attribute to ``line.name`` outside of the line loop, which would raise a
  ``NameError`` (``line`` undefined there); reverted to the value the Studio
  edit before it left in place (``o.line_ids``).

The "Comercio Exterior" (customs) block in these reports reads
``cfdi_vals['ext_trade_*']`` keys that no current python code populates;
those accesses are made safe with ``.get()`` here but will keep rendering
blank until that data extraction is reimplemented.
"""

import re

from odoo import api, SUPERUSER_ID

# (old, new) literal replacements safe to try on every affected document
# template: each is a no-op if the pattern isn't present.
LITERAL_FIXES = [
    (
        '<t t-call="web.external_layout" style="color:#000000">',
        '<t t-call="web.external_layout">',
    ),
    (
        "o._l10n_mx_edi_decode_cfdi()",
        "o.env['l10n_mx_edi.document']._decode_cfdi_attachment("
        "o.l10n_mx_edi_cfdi_attachment_id.raw)",
    ),
    (
        "bool(o._get_l10n_mx_edi_signed_edi_document())",
        "o.l10n_mx_edi_cfdi_state == 'sent'",
    ),
    (
        "o.l10n_mx_edi_cfdi_request in ('on_invoice', 'on_refund') "
        "and not is_cfdi_signed and o.edi_state != 'cancelled'",
        "o.move_type in ('out_invoice', 'out_refund') "
        "and not is_cfdi_signed and o.state != 'cancel'",
    ),
    (
        "o.sudo()._get_reconciled_info_JSON_values()",
        "o.sudo().invoice_payments_widget and "
        "o.sudo().invoice_payments_widget['content'] or []",
    ),
    (
        "o.l10n_mx_edi_origin",
        "o.l10n_mx_edi_cfdi_origin",
    ),
    (
        't-if="not line.display_type"',
        "t-if=\"line.display_type == 'product' or not line.display_type\"",
    ),
]

# view key -> account.document_tax_totals* template it t-calls, to migrate
# `<t t-set="tax_totals" t-value="json.loads(o.tax_totals_json)"/><t t-call="TMPL"/>`
# into `<t t-if="o.tax_totals" t-call="TMPL"><t t-set="tax_totals" .../><t t-set="currency" .../></t>`.
TAX_TOTALS_CALL_TARGETS = {
    "account.report_invoice_document_with_payments_copy_3_copy_2": "account.document_tax_totals",
    "account.report_invoice_document_with_payments_copy_3_copy_2_copy_1": "account.document_tax_totals",
    "account.report_invoice_document_with_payments_copy_3_copy_2_copy_1_copy_1": "account.document_tax_totals",
    "account.report_invoice_document_with_payments_copy_3_copy_2_copy_2": "account.document_tax_totals_copy_1",
    "account.report_invoice_document_with_payments_copy_3_copy_3": "account.document_tax_totals",
    "account.report_invoice_document_with_payments_copy_3_copy_3_copy_1": "account.document_tax_totals_copy_2",
    "account.report_invoice_document_copy_1": "account.document_tax_totals_copy_4",
    "account.report_invoice_document_copy_2": "account.document_tax_totals_copy_5",
    "account.report_invoice_document_copy_3": "account.document_tax_totals_copy_6",
    "account.report_invoice_document_copy_4": "account.document_tax_totals_copy_9",
}

# report action wrapper key -> document key: drop the
# `_get_name_invoice_report() == 'account.report_invoice_document'` gate so
# the (single-purpose) duplicated document always renders.
WRAPPER_GATE_TARGETS = {
    "account.report_invoice_with_payments_copy_8": "account.report_invoice_document_copy_1",
    "account.report_invoice_with_payments_copy_9": "account.report_invoice_document_copy_2",
    "account.report_invoice_with_payments_copy_10": "account.report_invoice_document_copy_3",
    "account.report_invoice_with_payments_copy_11": "account.report_invoice_document_copy_4",
}

# document_tax_totals* templates whose custom "Descuento" subtotal block was
# still using the pre-Odoo-17 `_get_tax_totals_json` shape (formatted_amount,
# groups_by_subtotal); rewritten below to use `_get_tax_totals_summary`
# (subtotals / tax_groups / *_currency) like Odoo 19 core does.
TAX_TOTALS_TEMPLATE = '''<t t-name="{name}">
            <!--
                Generic template to display tax totals in pdf reports.
                Used by invoices, SO and PO.

                ARGUMENTS:
                - tax_totals: dict in the form generated by account.move's _get_tax_totals.
            -->
            <t t-set="same_tax_base" t-value="tax_totals['same_tax_base']"/>
            <t t-foreach="tax_totals['subtotals']" t-as="subtotal">
                <tr class="border-black o_subtotal">
                    <td><strong t-esc="subtotal['name']"/></td>

                    <td class="text-end">
                        <span t-att-class="oe_subtotal_footer_separator" t-out="subtotal['base_amount_currency']" t-options="{{'widget': 'monetary', 'display_currency': currency}}"/>
                    </td>
                </tr>
                <t t-set="total_discount" t-value="0"/>
                <t t-if="o">
                    <t t-set="lines" t-value="o.invoice_line_ids"/>
                </t>
                <t t-if="doc">
                    <t t-set="lines" t-value="doc.order_line"/>
                </t>
                <t t-foreach="lines" t-as="line">
                    <t t-if="o">
                        <t t-set="quantity" t-value="line.quantity"/>
                    </t>
                    <t t-if="doc">
                        <t t-set="quantity" t-value="line.product_uom_qty"/>
                    </t>
                    <t t-set="line_discount_price_unit" t-value="line.price_unit * (line.discount / 100.0)"/>
                    <t t-set="line_discount" t-value="quantity * line_discount_price_unit"/>
                    <t t-set="total_discount" t-value="total_discount + line_discount"/>
                </t>
                <tr t-if="total_discount" class="border-black o_subtotal">
                    <td><strong>Descuento</strong></td>

                    <td class="text-end">
                        <span t-att-class="oe_subtotal_footer_separator" t-esc="round(total_discount, 2)" t-options="{{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: currency}}"/>
                    </td>
                </tr>

                <t t-foreach="subtotal['tax_groups']" t-as="tax_group">
                    <tr class="o_taxes">
                        <t t-if="same_tax_base or tax_group['display_base_amount_currency'] is False">
                            <td style="max-width: 200px;">
                                <span t-out="tax_group['group_name']"/>
                            </td>
                            <td class="text-end o_price_total">
                                <span class="text-nowrap" t-out="tax_group['tax_amount_currency']" t-options="{{'widget': 'monetary', 'display_currency': currency}}"/>
                            </td>
                        </t>
                        <t t-else="">
                            <td>
                                <span t-out="tax_group['group_name']"/>
                                <span> on </span>
                                <span class="text-nowrap" t-out="tax_group['display_base_amount_currency']" t-options="{{'widget': 'monetary', 'display_currency': currency}}"/>
                            </td>
                            <td class="text-end o_price_total">
                                <span class="text-nowrap" t-out="tax_group['tax_amount_currency']" t-options="{{'widget': 'monetary', 'display_currency': currency}}"/>
                            </td>
                        </t>
                    </tr>
                </t>
            </t>

            <!--Total amount with all taxes-->
            <tr class="border-black o_total">
                <td><strong>Total</strong></td>
                <td class="text-end">
                    <span t-out="tax_totals['total_amount_currency']" t-options="{{'widget': 'monetary', 'display_currency': currency}}"/>
                </td>
            </tr>
        </t>'''

TAX_TOTALS_TEMPLATES_TO_REWRITE = [
    "account.document_tax_totals_copy_1",
    "account.document_tax_totals_copy_2",
    "account.document_tax_totals_copy_4",
    "account.document_tax_totals_copy_5",
    "account.document_tax_totals_copy_6",
    "account.document_tax_totals_copy_9",
]


def _get_view(env, key):
    return env["ir.ui.view"].search([("key", "=", key)], limit=1)


def migrate(cr, version):
    env = api.Environment(cr, SUPERUSER_ID, {})

    for key, tmpl in TAX_TOTALS_CALL_TARGETS.items():
        view = _get_view(env, key)
        if not view:
            continue
        arch = view.arch

        old_call = (
            '<t t-set="tax_totals" t-value="json.loads(o.tax_totals_json)"/>\n'
        )
        # indentation before the paired <t t-call="TMPL"/> varies between
        # views, so match it loosely instead of hard-coding whitespace.
        marker = f'<t t-call="{tmpl}"/>'
        idx = arch.find(old_call)
        if idx != -1:
            rest = arch[idx + len(old_call):]
            call_idx = rest.find(marker)
            if call_idx != -1 and rest[:call_idx].strip() == "":
                indent = rest[:call_idx]
                old_block = old_call + indent + marker
                new_block = (
                    f'<t t-if="o.tax_totals" t-call="{tmpl}">\n'
                    f"{indent}    <t t-set=\"tax_totals\" t-value=\"o.tax_totals\"/>\n"
                    f"{indent}    <t t-set=\"currency\" t-value=\"o.currency_id\"/>\n"
                    f"{indent}</t>"
                )
                arch = arch.replace(old_block, new_block)

        for old, new in LITERAL_FIXES:
            if old in arch:
                arch = arch.replace(old, new)

        # guard direct cfdi_vals['ext_trade_*'] access (Comercio Exterior
        # block): no current code populates these keys, so this only avoids
        # a KeyError crash, it does not restore the missing data.
        arch = re.sub(
            r"cfdi_vals\['(ext_trade_[a-z_]+)'\]", r"cfdi_vals.get('\1')", arch
        )

        if arch != view.arch:
            view.write({"arch": arch})

    for wrapper_key, doc_key in WRAPPER_GATE_TARGETS.items():
        view = _get_view(env, wrapper_key)
        if not view:
            continue
        old = (
            "<t t-if=\"o._get_name_invoice_report() == "
            f"'account.report_invoice_document'\" t-call=\"{doc_key}\" t-lang=\"lang\"/>"
        )
        new = f'<t t-call="{doc_key}" t-lang="lang"/>'
        if old in view.arch:
            view.write({"arch": view.arch.replace(old, new)})

    for key in TAX_TOTALS_TEMPLATES_TO_REWRITE:
        view = _get_view(env, key)
        if view:
            view.write({"arch": TAX_TOTALS_TEMPLATE.format(name=key)})

    _fix_internal_note_overlay(env)


def _fix_internal_note_overlay(env):
    """Drop the broken `line.internal_note` column and the stray
    `t-field="line.name"` header attribute added by the Studio overlay on
    top of `account.report_invoice_document_copy_1` (used by "Factura
    Nacional Veco copy(8)")."""
    parent = _get_view(env, "account.report_invoice_document_copy_1")
    if not parent:
        return
    overlay = env["ir.ui.view"].search([
        ("inherit_id", "=", parent.id),
        ("name", "like", "Odoo Studio:"),
    ], limit=1)
    if not overlay:
        return
    arch = overlay.arch

    remove_note_column = (
        '  <xpath expr="/t/t/div/table/thead/tr/th[2]" position="after">\n'
        "    <th>\n"
        "      <span>Nota interna</span>\n"
        "    </th>\n"
        "  </xpath>\n"
        '  <xpath expr="/t/t/div/table/tbody/t[3]/tr/t[1]/td[2]" position="after">\n'
        "    <td>\n"
        '      <span t-field="line.internal_note"/>\n'
        "    </td>\n"
        "  </xpath>\n"
    )
    if remove_note_column in arch:
        arch = arch.replace(remove_note_column, "")

    remove_bad_attribute = (
        '  <xpath expr="/t[1]/t[1]/div[1]/div[7]/div[1]/span[1]" position="attributes">\n'
        '    <attribute name="t-field">line.name</attribute>\n'
        "  </xpath>\n"
    )
    if remove_bad_attribute in arch:
        arch = arch.replace(remove_bad_attribute, "")

    if arch != overlay.arch:
        overlay.write({"arch": arch})
